// <auto-generated />
using System;
using K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace K22CNT4_PhamThiThuHuyen_2210900030_DATN.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260123165023_AddTransportMethodToOrder")]
    partial class AddTransportMethodToOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Admin");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__ADMINS__3214EC274C042050");

                    b.ToTable("ADMINS");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Icon")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ICON");

                    b.Property<byte?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("ISACTIVE");

                    b.Property<byte?>("Isdelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("ISDELETE");

                    b.Property<string>("MetaDesc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_DESC");

                    b.Property<string>("MetaKeyword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_KEYWORD");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("META_TITLE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<long?>("Parentid")
                        .HasColumnType("bigint")
                        .HasColumnName("PARENTID");

                    b.Property<string>("Slug")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("SLUG");

                    b.HasKey("Id")
                        .HasName("PK__CATEGORY__A50F9896210394B9");

                    b.HasIndex("Parentid");

                    b.ToTable("CATEGORY");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Color", b =>
                {
                    b.Property<long>("Colorid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Colorid"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODE");

                    b.Property<byte?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("ISACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.HasKey("Colorid")
                        .HasName("PK__COLOR__6FDDF3C465CC4824");

                    b.ToTable("COLOR");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Contact", b =>
                {
                    b.Property<long>("Contactid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Contactid"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("FULLNAME");

                    b.Property<byte?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("IS_READ");

                    b.Property<byte?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("ISACTIVE");

                    b.Property<byte?>("Isdelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("ISDELETE");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("ntext")
                        .HasColumnName("MESSAGE");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PHONE");

                    b.Property<string>("Reply")
                        .HasColumnType("ntext")
                        .HasColumnName("REPLY");

                    b.Property<DateTime?>("ReplyDate")
                        .HasColumnType("datetime")
                        .HasColumnName("REPLY_DATE");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SUBJECT");

                    b.HasKey("Contactid")
                        .HasName("PK__CONTACT__79911868EA517AC6");

                    b.ToTable("CONTACT");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Customer", b =>
                {
                    b.Property<long>("Customerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Customerid"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("Avatar")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("AVATAR");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("EMAIL");

                    b.Property<byte?>("Isdelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("ISDELETE");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PHONE");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("CUSTOMER")
                        .HasColumnName("USER_TYPE");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Customerid")
                        .HasName("PK__CUSTOMER__61DBD7885F7E911F");

                    b.HasIndex(new[] { "Email" }, "UQ__CUSTOMER__161CF7247B92D8CB")
                        .IsUnique()
                        .HasFilter("[EMAIL] IS NOT NULL");

                    b.HasIndex(new[] { "Username" }, "UQ__CUSTOMER__B15BE12EF6D38386")
                        .IsUnique();

                    b.ToTable("CUSTOMER");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Material", b =>
                {
                    b.Property<long>("Materialid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Materialid"));

                    b.Property<byte?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("ISACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<string>("Notes")
                        .HasColumnType("ntext")
                        .HasColumnName("NOTES");

                    b.HasKey("Materialid")
                        .HasName("PK__MATERIAL__278B51D527E482C7");

                    b.ToTable("MATERIAL");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Order", b =>
                {
                    b.Property<long>("Ordersid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Ordersid"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ADDRESS");

                    b.Property<long?>("Customerid")
                        .HasColumnType("bigint")
                        .HasColumnName("CUSTOMERID");

                    b.Property<byte?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("ISACTIVE");

                    b.Property<byte?>("Isdelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("ISDELETE");

                    b.Property<string>("NameReceiver")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME_RECEIVER");

                    b.Property<DateTime?>("OrdersDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ORDERS_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PHONE");

                    b.Property<decimal?>("TotalMoney")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("TOTAL_MONEY");

                    b.Property<long?>("TransportMethodid")
                        .HasColumnType("bigint");

                    b.HasKey("Ordersid")
                        .HasName("PK__ORDERS__B0B1A3EBEB50343D");

                    b.HasIndex("Customerid");

                    b.HasIndex("TransportMethodid");

                    b.ToTable("ORDERS");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.OrdersDetail", b =>
                {
                    b.Property<long>("OrdersDetailsid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrdersDetailsid"));

                    b.Property<long>("Ordersid")
                        .HasColumnType("bigint")
                        .HasColumnName("ORDERSID");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("PRICE");

                    b.Property<long>("Productvariantid")
                        .HasColumnType("bigint")
                        .HasColumnName("PRODUCTVARIANTID");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("QUANTITY");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("TOTAL");

                    b.HasKey("OrdersDetailsid")
                        .HasName("PK__ORDERS_D__E795C3F15F283861");

                    b.HasIndex("Ordersid");

                    b.HasIndex("Productvariantid");

                    b.ToTable("ORDERS_DETAILS");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.PayMethod", b =>
                {
                    b.Property<long>("PayMethodid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PayMethodid"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<byte?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("ISACTIVE");

                    b.Property<byte?>("Isdelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("ISDELETE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<string>("Notes")
                        .HasColumnType("ntext")
                        .HasColumnName("NOTES");

                    b.HasKey("PayMethodid")
                        .HasName("PK__PAY_METH__55A067C94A097C18");

                    b.ToTable("PAY_METHOD");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("Categoryid")
                        .HasColumnType("bigint")
                        .HasColumnName("CATEGORYID");

                    b.Property<string>("Contents")
                        .HasColumnType("ntext")
                        .HasColumnName("CONTENTS");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("ntext")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("GENDER");

                    b.Property<byte?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("ISACTIVE");

                    b.Property<byte?>("Isdelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("ISDELETE");

                    b.Property<byte?>("Ishome")
                        .HasColumnType("tinyint")
                        .HasColumnName("ISHOME");

                    b.Property<byte?>("Issale")
                        .HasColumnType("tinyint")
                        .HasColumnName("ISSALE");

                    b.Property<byte?>("Istopsale")
                        .HasColumnType("tinyint")
                        .HasColumnName("ISTOPSALE");

                    b.Property<string>("MetaDesc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_DESC");

                    b.Property<string>("MetaKeyword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("META_KEYWORD");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("META_TITLE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("NAME");

                    b.Property<decimal?>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("PRICE");

                    b.Property<string>("Slug")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("SLUG");

                    b.HasKey("Id")
                        .HasName("PK__PRODUCT__34980AA2D4885042");

                    b.HasIndex("Categoryid");

                    b.ToTable("PRODUCT");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.ProductImage", b =>
                {
                    b.Property<long>("ProductImagesid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductImagesid"));

                    b.Property<long?>("Colorid")
                        .HasColumnType("bigint")
                        .HasColumnName("COLORID");

                    b.Property<byte?>("Isdefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("ISDEFAULT");

                    b.Property<long>("Productid")
                        .HasColumnType("bigint")
                        .HasColumnName("PRODUCTID");

                    b.Property<string>("Urlimg")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("URLIMG");

                    b.HasKey("ProductImagesid")
                        .HasName("PK__PRODUCT___BE142DD3D08164A2");

                    b.HasIndex("Colorid");

                    b.HasIndex("Productid");

                    b.ToTable("PRODUCT_IMAGES");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.ProductVariant", b =>
                {
                    b.Property<long>("ProductVariantid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductVariantid"));

                    b.Property<long>("Colorid")
                        .HasColumnType("bigint")
                        .HasColumnName("COLORID");

                    b.Property<byte?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("ISACTIVE");

                    b.Property<long>("Materialid")
                        .HasColumnType("bigint")
                        .HasColumnName("MATERIALID");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("PRICE");

                    b.Property<long>("Productid")
                        .HasColumnType("bigint")
                        .HasColumnName("PRODUCTID");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("QUANTITY");

                    b.Property<long>("Sizeid")
                        .HasColumnType("bigint")
                        .HasColumnName("SIZEID");

                    b.HasKey("ProductVariantid")
                        .HasName("PK__PRODUCT___1342E27527D2FC8E");

                    b.HasIndex("Colorid");

                    b.HasIndex("Materialid");

                    b.HasIndex("Productid");

                    b.HasIndex("Sizeid");

                    b.ToTable("PRODUCT_VARIANT");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Review", b =>
                {
                    b.Property<long>("Reviewid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Reviewid"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("ntext")
                        .HasColumnName("CONTENT");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long?>("Customerid")
                        .HasColumnType("bigint")
                        .HasColumnName("CUSTOMERID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("FULLNAME");

                    b.Property<byte?>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("IS_APPROVED");

                    b.Property<byte?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("ISACTIVE");

                    b.Property<byte?>("Isdelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("ISDELETE");

                    b.Property<long>("Productid")
                        .HasColumnType("bigint")
                        .HasColumnName("PRODUCTID");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint")
                        .HasColumnName("RATING");

                    b.Property<string>("Reply")
                        .HasColumnType("ntext")
                        .HasColumnName("REPLY");

                    b.Property<DateTime?>("ReplyDate")
                        .HasColumnType("datetime")
                        .HasColumnName("REPLY_DATE");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TITLE");

                    b.HasKey("Reviewid")
                        .HasName("PK__REVIEW__DDDCEB4A57C3AC9B");

                    b.HasIndex("Customerid");

                    b.HasIndex("Productid");

                    b.ToTable("REVIEW");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Size", b =>
                {
                    b.Property<long>("Sizeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Sizeid"));

                    b.Property<int?>("AgeFrom")
                        .HasColumnType("int")
                        .HasColumnName("AGE_FROM");

                    b.Property<int?>("AgeTo")
                        .HasColumnType("int")
                        .HasColumnName("AGE_TO");

                    b.Property<byte?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("ISACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.HasKey("Sizeid")
                        .HasName("PK__SIZE__903CA348CE388A5F");

                    b.ToTable("SIZE");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.TransportMethod", b =>
                {
                    b.Property<long>("TransportMethodid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransportMethodid"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<byte?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("ISACTIVE");

                    b.Property<byte?>("Isdelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("ISDELETE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<string>("Notes")
                        .HasColumnType("ntext")
                        .HasColumnName("NOTES");

                    b.HasKey("TransportMethodid")
                        .HasName("PK__TRANSPOR__15CD30836FAFC2D8");

                    b.ToTable("TRANSPORT_METHOD");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Category", b =>
                {
                    b.HasOne("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Category", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("Parentid")
                        .HasConstraintName("FK_CATEGORY_PARENT");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Order", b =>
                {
                    b.HasOne("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("Customerid")
                        .HasConstraintName("FK_ORDERS_CUSTOMER");

                    b.HasOne("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.TransportMethod", "TransportMethod")
                        .WithMany()
                        .HasForeignKey("TransportMethodid");

                    b.Navigation("Customer");

                    b.Navigation("TransportMethod");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.OrdersDetail", b =>
                {
                    b.HasOne("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Order", "Orders")
                        .WithMany("OrdersDetails")
                        .HasForeignKey("Ordersid")
                        .IsRequired()
                        .HasConstraintName("FK_OD_ORDERS");

                    b.HasOne("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.ProductVariant", "Productvariant")
                        .WithMany("OrdersDetails")
                        .HasForeignKey("Productvariantid")
                        .IsRequired()
                        .HasConstraintName("FK_OD_VARIANT");

                    b.Navigation("Orders");

                    b.Navigation("Productvariant");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Product", b =>
                {
                    b.HasOne("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("Categoryid")
                        .HasConstraintName("FK_PRODUCT_CATEGORY");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.ProductImage", b =>
                {
                    b.HasOne("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Color", "Color")
                        .WithMany("ProductImages")
                        .HasForeignKey("Colorid")
                        .HasConstraintName("FK_PI_COLOR");

                    b.HasOne("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("Productid")
                        .IsRequired()
                        .HasConstraintName("FK_PI_PRODUCT");

                    b.Navigation("Color");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.ProductVariant", b =>
                {
                    b.HasOne("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Color", "Color")
                        .WithMany("ProductVariants")
                        .HasForeignKey("Colorid")
                        .IsRequired()
                        .HasConstraintName("FK_PV_COLOR");

                    b.HasOne("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Material", "Material")
                        .WithMany("ProductVariants")
                        .HasForeignKey("Materialid")
                        .IsRequired()
                        .HasConstraintName("FK_PV_MATERIAL");

                    b.HasOne("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("Productid")
                        .IsRequired()
                        .HasConstraintName("FK_PV_PRODUCT");

                    b.HasOne("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Size", "Size")
                        .WithMany("ProductVariants")
                        .HasForeignKey("Sizeid")
                        .IsRequired()
                        .HasConstraintName("FK_PV_SIZE");

                    b.Navigation("Color");

                    b.Navigation("Material");

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Review", b =>
                {
                    b.HasOne("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("Customerid")
                        .HasConstraintName("FK_REVIEW_CUSTOMER");

                    b.HasOne("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("Productid")
                        .IsRequired()
                        .HasConstraintName("FK_REVIEW_PRODUCT");

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Category", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Color", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Material", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Order", b =>
                {
                    b.Navigation("OrdersDetails");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("ProductVariants");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.ProductVariant", b =>
                {
                    b.Navigation("OrdersDetails");
                });

            modelBuilder.Entity("K22CNT4_PhamThiThuHuyen_2210900030_DATN.Models.EF.Size", b =>
                {
                    b.Navigation("ProductVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
